.\" vim: filetype=groff
.\" libn.7.mdoc
.\" Christian Koch <cfkoch@sdf.lonestar.org>
.\" =====
.Dd August 1, 2014
.Dt LIBN 7
.Os
.\" =====
.Sh NAME
.Nm libn
.Nd Convenient routines for C
.\" =====
.Sh SYNOPSIS
.Fd "#include <libn.h>"
.\" =====
.Sh DESCRIPTION
.Nm
is a set of functions.
.\" =====
.Sh SEE ALSO
.Xr narray 3 ,
.Xr nhash 3 ,
.Xr nstring 3
.\" =====
.Sh HISTORY
.Nm
was created by Christian Koch in August, 2014.
.\" =====
.Sh AUTHORS
.An "Christian Koch" Aq cfkoch@sdf.lonestar.org
