.\" vim: filetype=groff
.\" nhash.3.mdoc
.\" Christian Koch <cfkoch@sdf.lonestar.org>
.\" =====
.Dd August 1, 2014
.Dt NHASH 3
.Os
.\" =====
.Sh NAME
.Nm nhash
.Nd libn routines for manipulating hashes
.\" =====
.Sh SYNOPSIS
.Fd "#include <libn.h>"
.Ft "nhash *"
.Fn nhash_new "void"
.Ft "void"
.Fn nhash_free "nhash *hash"
.Ft "void"
.Fn nhash_set "nhash *hash , const char *key , const void *ptr"
.Ft "void *"
.Fn nhash_get "const nhash *hash , const char *key"
.Ft void
.Fn nhash_delete "nhash *hash , const char *key"
.Ft char *
.Fn nhash_inspect "const nhash *hash"
.Ft "nstringhash *"
.Fn nstringhash_new "void"
.Ft "void"
.Fn nstringhash_free "nstringhash *hash"
.Ft "void"
.Fn nstringhash_set "nstringhash *hash , const char *key , const char *value"
.Ft "char *"
.Fn nstringhash_get "const nstringhash *hash , const char *key"
.Ft void
.Fn nstringhash_delete "nstringhash *hash , const char *key"
.Ft char *
.Fn nstringhash_inspect "const nstringhash *hash"
.\" ====="
.Sh DESCRIPTION
.Nm
is an opaque structure which represents a hash.
.\" =====
.Sh EXAMPLES
TODO
.\" =====
.Sh SEE ALSO
.Xr narray 3 ,
.Xr nset 3 ,
.Xr nstring 3
.\" =====
.Sh HISTORY
The
.Nm
structure and related functions first appeared in
.Nm libn
version 0.0.0.
.\" =====
.Sh AUTHORS
.An "Christian Koch" Aq cfkoch@sdf.lonestar.org
.\" =====
.\".Sh BUGS
